### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by keirlawson** [ovotech/ciris-aws-ssm#208]
Given bintray is going away it would be great to publish this to Maven Central so that it is still useable.

**Comment by barryoneill** [comment]
Hi - We have a failed build with `https://dl.bintray.com/ovotech/maven/com/ovoenergy/ciris-aws-ssm_2.13/1.0.0/ciris-aws-ssm_2.13-1.0.0.pom` - is it possible it's related to this?  Bintray will be gone on May 1st..

**Comment by barryoneill** [comment]
yeah, seems related to this

https://github.com/ovotech/ciris-aws-ssm/issues/208
Apr 26, 2021
Unresolved incident: Schedule brown-out session on April 26th 6AM to 2PM Pacific Daylight Time.

**Comment by keirlawson** [comment]
Closing this as the library is now available via public artifactory repo

**Comment by barryoneill** [comment]
@keirlawson - is there any plan to publish this to maven central (i.e. sonatype)? 

It's not quite clear who owns the `Kaluza artifactory` repository.

**Comment by keirlawson** [comment]
I don't believe so, Kaluza (https://www.kaluza.com/) is a sub-company of Ovo, so its the same people owning/maintaining at the end of the day :)

**Comment by barryoneill** [comment]
Fair enough;  I'm always suspicious of READMEs that casually just ask people to add new resolvers into their ecosystem :)
