### ISSUE TITLE
Publish against Ciris 3.2.0

### ISSUE THREAD

**Issue by barryoneill** [ovotech/ciris-aws-ssm#363]
Unfortunately ciris 3.2.0 is not binary compatible with the 2.x release.  It would be great if `ciris-aws-ssm` could be built for the newer release (which would require a scala bump to 3.2.2).

**Comment by keirlawson** [comment]
6.0.0 has now been released that depends on 3.2.0, thanks for contributing!

**Comment by barryoneill** [comment]
@keirlawson thank you so much!
